In [24]:
#Python program to demonstrate basic array characteristics
import numpy as np

#creating array object
arr = np.array([[1, 2, 3],
                [4, 2, 5]])

#printing type of arr object
print ("Array is of type:\n", type(arr))

#printing array dimensions(axes)
print ("\nNumber of dimensions:\n", arr.ndim)

#printing shape of array
print ("\nShape of array:\n", arr.shape)

#printing total number of elements(size) of an array
print ("\nSize of array:\n", arr.size)

#printing type of elements in array
print ("\nArray stores elements of type:\n", arr.dtype)

Array is of type:
 <class 'numpy.ndarray'>

Number of dimensions:
 2

Shape of array:
 (2, 3)

Size of array:
 6

Array stores elements of type:
 int32


In [26]:
#Python program to demonstrate array creation techniques
import numpy as np

#creating array from list with type float
a = np.array([[1, 2, 4],
              [5, 8, 7]], dtype = 'float')
print ("\nArray created using passed list:\n", a)

#creating array from tuple
b = np.array((1, 3, 2))
print ("\nArray created using passed tuple:\n", b)

#creating a 3*4 array with all 0s
c = np.zeros((3, 4))
print ("\nArray initialized with all zeros:\n", c)

#create a constant value array of complex type
d = np.full((3, 3), 6, dtype = 'complex')
print ("\nAn array whose type is complex and initialized with all 6s:\n", d)

#create an array with random values
e = np.random.random((2, 2))
print ("\nA random array:\n", e)

#create a sequence of integers from 0 to 30 with steps of 5
f = np.arange(0, 30, 5) #in this case, the step-size is given
print ("\nA sequential array with steps of 5:\n", f)

#create a sequence of 10 values in range 0 t0 5
g = np.linspace(0, 5, 10) #in this case, the number of elements is given
print ("\nA sequential array with 10 values between 0 and 5:\n", g)

#reshaping a 3*4 array into a 2*3*3 array
arr = np.array([[1, 2, 3, 4],
                [5, 2, 4, 2],
                [1, 2, 0, 1]])
newarr = arr.reshape(2, 2, 3)
print ("\nOriginal array:\n", arr)
print ("\nReshaped array:\n", newarr)

#flatten array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
rowarr = arr.flatten()
rowarr1 = arr.flatten('C')
colarr = arr.flatten('F')
print ("\nOriginal array:\n", arr)
print ("\nFlattened array:\n", rowarr)
print ("\nFlattened array:\n", rowarr1)
print ("\nFlattened array:\n", colarr)


Array created using passed list:
 [[ 1.  2.  4.]
 [ 5.  8.  7.]]

Array created using passed tuple:
 [1 3 2]

Array initialized with all zeros:
 [[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]

An array whose type is complex and initialized with all 6s:
 [[ 6.+0.j  6.+0.j  6.+0.j]
 [ 6.+0.j  6.+0.j  6.+0.j]
 [ 6.+0.j  6.+0.j  6.+0.j]]

A random array:
 [[ 0.91101073  0.31639031]
 [ 0.10347896  0.42754968]]

A sequential array with steps of 5:
 [ 0  5 10 15 20 25]

A sequential array with 10 values between 0 and 5:
 [ 0.          0.55555556  1.11111111  1.66666667  2.22222222  2.77777778
  3.33333333  3.88888889  4.44444444  5.        ]

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]

Reshaped array:
 [[[1 2 3]
  [4 5 2]]

 [[4 2 1]
  [2 0 1]]]

Original array:
 [[1 2 3]
 [4 5 6]]

Flattened array:
 [1 2 3 4 5 6]

Flattened array:
 [1 2 3 4 5 6]

Flattened array:
 [1 4 2 5 3 6]


In [28]:
#Python program to demonstrate indexing in numpy
import numpy as np

#an exemplar array
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

#slicing
temp = arr[:2, ::2]
print ("\nArray with the 1st 2 rows and alternate columns(0 and 2):\n", temp)

#integer array indexing example
temp = arr[[0, 1, 2, 3],
           [3, 2, 1, 0]]
print ("\nElements at indices (0, 3), (1, 2), (2, 1) and (3, 0):\n", temp)

#boolean array indexing example
cond = arr > 0 #cond is a boolean array
temp = arr[cond]
print ("\nElements greater than 0:\n", temp)


Array with the 1st 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (0, 3), (1, 2), (2, 1) and (3, 0):
 [ 4.  6.  0.  3.]

Elements greater than 0:
 [ 2.   4.   4.   6.   2.6  7.   8.   3.   4.   2. ]


In [36]:
#Python program to demonstrate basic operations on single array
import numpy as np

a = np.array([1, 2, 5, 3])

#add 1 to every element
print ("\nAdding 1 to every element:\n", a + 1)

#subtract 3 from each element
print ("\nSubtracting 3 from each element:\n", a - 3)

#multiply each element by 10
print ("\nMultiplying each element y 10:\n", a * 10)

#square each element
print ("\nSquaring each element:\n", a ** 2)

#modify existing array
a *= 2
print ("\nDoubled element of each array:\n", a)

#transpose of array
a = np.array([[1, 2, 3],
              [3, 4, 5],
              [9, 6, 0]])
print ("\nOriginal array:\n", a)
print ("\nTranspose of array:\n", a.T)


Adding 1 to every element:
 [2 3 6 4]

Subtracting 3 from each element:
 [-2 -1  2  0]

Multiplying each element y 10:
 [10 20 50 30]

Squaring each element:
 [ 1  4 25  9]

Doubled element of each array:
 [ 2  4 10  6]

Original array:
 [[1 2 3]
 [3 4 5]
 [9 6 0]]

Transpose of array:
 [[1 3 9]
 [2 4 6]
 [3 5 0]]


In [44]:
#Python program to demonstrate unary operations in Numpy
import numpy as np

arr = np.array([[1, 5, 6],
                [4, 7, 2],
                [3, 1, 9]])

#maximum element of array
print ("\nLargest element is:\n", arr.max())
print ("\nRow-wise maximum elements:", arr.max(axis = 1))
print ("\nColumn-wise maximum elements:", arr.max(axis = 0))

#minimum element of array
print ("\nSmallest element is:\n", arr.min())
print ("\nRow-wise minimum elements:", arr.min(axis = 1))
print ("\nColumn-wise minimum elements:", arr.min(axis = 0))

#sum of array elements
print ("\nSum of all array elements:\n", arr.sum())

#cumulative sum along each row and/or column
print ("\nCumulative sum along each row:\n", arr.cumsum(axis = 1))
print ("\nCumulative sum along each column:\n", arr.cumsum(axis = 0))


Largest element is:
 9

Row-wise maximum elements: [6 7 9]

Column-wise maximum elements: [4 7 9]

Smallest element is:
 1

Row-wise minimum elements: [1 2 1]

Column-wise minimum elements: [1 1 2]

Sum of all array elements:
 38

Cumulative sum along each row:
 [[ 1  6 12]
 [ 4 11 13]
 [ 3  4 13]]

Cumulative sum along each column:
 [[ 1  5  6]
 [ 5 12  8]
 [ 8 13 17]]


In [47]:
#Python program to demonstrate binary operations in NumPy
import numpy as np

a = np.array([[1, 2],
              [3, 4]])
b = np.array([[4, 3],
              [2, 1]])

#add arrays (element-wise addition)
print ("\nArray Sum:\n", a + b)

#add arrays (element-wise multiplication)
print ("\nArray Multiplication:\n", a * b)

#Matrix Multiplication
print ("\nMatrix multiplication:\n", a.dot(b))


Array Sum:
 [[5 5]
 [5 5]]

Array Multiplication:
 [[4 6]
 [6 4]]

Matrix multiplication:
 [[ 8  5]
 [20 13]]


In [51]:
#Python program to demonstrate universal functions in NumPy
import numpy as np

#create an array of sine values
a = np.array([0, np.pi/2, np.pi])
print ("\nSine values of array elements:\n", np.sin(a))

#exponential values
a = np.array([0, 1, 2, 3])
print ("\nExponent of array elements:\n", np.exp(a))

#square root of array values
print ("\nSquare root of array elements:\n", np.sqrt(a))


Sine values of array elements:
 [  0.00000000e+00   1.00000000e+00   1.22464680e-16]

Exponent of array elements:
 [  1.           2.71828183   7.3890561   20.08553692]

Square root of array elements:
 [ 0.          1.          1.41421356  1.73205081]


In [55]:
#Python program to demonstrate sorting in NumPy
import numpy as np
a = np.array([[1, 4, 2],
              [3, 4, 6],
              [0, -1, 5]])

#sorted array
print ("\nArray elements in sorted order:\n", np.sort(a, axis = None))

#sort array row-wise and column-wise
print ("\nRow-wise sorted array:\n", np.sort(a, axis = 1))
print ("\nColumn-wise sorted array:\n", np.sort(a, axis = 0))

#example to show sorting of structured array
##set alias names for dtypes
dtypes = [('name', 'S10'), ('grad_year', int), ('cgpa', float)]
##values to be put in array
values = [('Hrithik', 2009, 8.5), ('Ajay', 2008, 8.7), ('Pankaj', 2008, 7.9), ('Aakash', 2009, 9.0)]
##creating array
arr = np.array(values, dtype = dtypes)
print ("\nArray sorted by names:\n", np.sort(arr, order = 'name'))
print ("\nArray sorted by graduation year and then CGPA:\n", np.sort(arr, order = ['grad_year', 'cgpa']))


Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]

Row-wise sorted array:
 [[ 1  2  4]
 [ 3  4  6]
 [-1  0  5]]

Column-wise sorted array:
 [[ 0 -1  2]
 [ 1  4  5]
 [ 3  4  6]]

Array sorted by names:
 [(b'Aakash', 2009,  9. ) (b'Ajay', 2008,  8.7) (b'Hrithik', 2009,  8.5)
 (b'Pankaj', 2008,  7.9)]

Array sorted by graduation year and then CGPA:
 [(b'Pankaj', 2008,  7.9) (b'Ajay', 2008,  8.7) (b'Hrithik', 2009,  8.5)
 (b'Aakash', 2009,  9. )]
